- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  retries: 2
  delay: 5

- name: Install sni proxy
  ansible.builtin.apt: 
    name: sniproxy
  retries: 3
  delay: 10
  become: true

- name: Template sniproxy config
  become: true
  ansible.builtin.template:
    src: sniproxy.conf.j2
    dest: /etc/sniproxy.conf
    owner: root
    group: root
    mode: "a+x"

- name: Start service
  ansible.builtin.service:
    name: sniproxy
    state: started
    enabled: yes
